# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GC_GS.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GC_GS.proto',
  package='GC_GS',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0bGC_GS.proto\x12\x05GC_GS\"j\n\nTokenLogin\x12-\n\x05msgid\x18\x01 \x01(\x0e\x32\x0c.GC_GS.MsgID:\x10GC2GS_TokenLogin\x12\x0c\n\x04mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\"E\n\x08\x45rrorMsg\x12(\n\x05msgid\x18\x01 \x01(\x0e\x32\x0c.GC_GS.MsgID:\x0bGS2GC_Error\x12\x0f\n\x07\x65rrorid\x18\x02 \x01(\x05*0\n\x05MsgID\x12\x15\n\x10GC2GS_TokenLogin\x10\xc9\x01\x12\x10\n\x0bGS2GC_Error\x10\xca\x01')
)

_MSGID = _descriptor.EnumDescriptor(
  name='MsgID',
  full_name='GC_GS.MsgID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GC2GS_TokenLogin', index=0, number=201,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GS2GC_Error', index=1, number=202,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=201,
  serialized_end=249,
)
_sym_db.RegisterEnumDescriptor(_MSGID)

MsgID = enum_type_wrapper.EnumTypeWrapper(_MSGID)
GC2GS_TokenLogin = 201
GS2GC_Error = 202



_TOKENLOGIN = _descriptor.Descriptor(
  name='TokenLogin',
  full_name='GC_GS.TokenLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='GC_GS.TokenLogin.msgid', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=201,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mail', full_name='GC_GS.TokenLogin.mail', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='GC_GS.TokenLogin.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='GC_GS.TokenLogin.token', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=128,
)


_ERRORMSG = _descriptor.Descriptor(
  name='ErrorMsg',
  full_name='GC_GS.ErrorMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='GC_GS.ErrorMsg.msgid', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=202,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorid', full_name='GC_GS.ErrorMsg.errorid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=199,
)

_TOKENLOGIN.fields_by_name['msgid'].enum_type = _MSGID
_ERRORMSG.fields_by_name['msgid'].enum_type = _MSGID
DESCRIPTOR.message_types_by_name['TokenLogin'] = _TOKENLOGIN
DESCRIPTOR.message_types_by_name['ErrorMsg'] = _ERRORMSG
DESCRIPTOR.enum_types_by_name['MsgID'] = _MSGID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TokenLogin = _reflection.GeneratedProtocolMessageType('TokenLogin', (_message.Message,), dict(
  DESCRIPTOR = _TOKENLOGIN,
  __module__ = 'GC_GS_pb2'
  # @@protoc_insertion_point(class_scope:GC_GS.TokenLogin)
  ))
_sym_db.RegisterMessage(TokenLogin)

ErrorMsg = _reflection.GeneratedProtocolMessageType('ErrorMsg', (_message.Message,), dict(
  DESCRIPTOR = _ERRORMSG,
  __module__ = 'GC_GS_pb2'
  # @@protoc_insertion_point(class_scope:GC_GS.ErrorMsg)
  ))
_sym_db.RegisterMessage(ErrorMsg)


# @@protoc_insertion_point(module_scope)
