# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GS_LS.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GS_LS.proto',
  package='GS_LS',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0bGS_LS.proto\x12\x05GS_LS\"h\n\x0b\x41skRegister\x12.\n\x05msgid\x18\x01 \x01(\x0e\x32\x0c.GS_LS.MsgID:\x11GS2LS_AskRegister\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\r\n\x05state\x18\x04 \x01(\x05\"E\n\x08\x45rrorMsg\x12(\n\x05msgid\x18\x01 \x01(\x0e\x32\x0c.GS_LS.MsgID:\x0bGS2LS_Error\x12\x0f\n\x07\x65rrorid\x18\x02 \x01(\t\"k\n\nCheckLogin\x12-\n\x05msgid\x18\x01 \x01(\x0e\x32\x0c.GS_LS.MsgID:\x10GS2LS_CheckLogin\x12\x0c\n\x04mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\x05*H\n\x05MsgID\x12\x16\n\x11GS2LS_AskRegister\x10\xe8\x07\x12\x10\n\x0bGS2LS_Error\x10\xe9\x07\x12\x15\n\x10GS2LS_CheckLogin\x10\xea\x07')
)

_MSGID = _descriptor.EnumDescriptor(
  name='MsgID',
  full_name='GS_LS.MsgID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GS2LS_AskRegister', index=0, number=1000,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GS2LS_Error', index=1, number=1001,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GS2LS_CheckLogin', index=2, number=1002,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=308,
  serialized_end=380,
)
_sym_db.RegisterEnumDescriptor(_MSGID)

MsgID = enum_type_wrapper.EnumTypeWrapper(_MSGID)
GS2LS_AskRegister = 1000
GS2LS_Error = 1001
GS2LS_CheckLogin = 1002



_ASKREGISTER = _descriptor.Descriptor(
  name='AskRegister',
  full_name='GS_LS.AskRegister',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='GS_LS.AskRegister.msgid', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='GS_LS.AskRegister.host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='GS_LS.AskRegister.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='GS_LS.AskRegister.state', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=126,
)


_ERRORMSG = _descriptor.Descriptor(
  name='ErrorMsg',
  full_name='GS_LS.ErrorMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='GS_LS.ErrorMsg.msgid', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errorid', full_name='GS_LS.ErrorMsg.errorid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=197,
)


_CHECKLOGIN = _descriptor.Descriptor(
  name='CheckLogin',
  full_name='GS_LS.CheckLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgid', full_name='GS_LS.CheckLogin.msgid', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1002,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mail', full_name='GS_LS.CheckLogin.mail', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='GS_LS.CheckLogin.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='GS_LS.CheckLogin.result', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=306,
)

_ASKREGISTER.fields_by_name['msgid'].enum_type = _MSGID
_ERRORMSG.fields_by_name['msgid'].enum_type = _MSGID
_CHECKLOGIN.fields_by_name['msgid'].enum_type = _MSGID
DESCRIPTOR.message_types_by_name['AskRegister'] = _ASKREGISTER
DESCRIPTOR.message_types_by_name['ErrorMsg'] = _ERRORMSG
DESCRIPTOR.message_types_by_name['CheckLogin'] = _CHECKLOGIN
DESCRIPTOR.enum_types_by_name['MsgID'] = _MSGID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AskRegister = _reflection.GeneratedProtocolMessageType('AskRegister', (_message.Message,), dict(
  DESCRIPTOR = _ASKREGISTER,
  __module__ = 'GS_LS_pb2'
  # @@protoc_insertion_point(class_scope:GS_LS.AskRegister)
  ))
_sym_db.RegisterMessage(AskRegister)

ErrorMsg = _reflection.GeneratedProtocolMessageType('ErrorMsg', (_message.Message,), dict(
  DESCRIPTOR = _ERRORMSG,
  __module__ = 'GS_LS_pb2'
  # @@protoc_insertion_point(class_scope:GS_LS.ErrorMsg)
  ))
_sym_db.RegisterMessage(ErrorMsg)

CheckLogin = _reflection.GeneratedProtocolMessageType('CheckLogin', (_message.Message,), dict(
  DESCRIPTOR = _CHECKLOGIN,
  __module__ = 'GS_LS_pb2'
  # @@protoc_insertion_point(class_scope:GS_LS.CheckLogin)
  ))
_sym_db.RegisterMessage(CheckLogin)


# @@protoc_insertion_point(module_scope)
